import { createHash } from 'node:crypto';
export type HashHex=string; export type StepMode='Exact'|'Stutter'|'SafeRefined';
export interface SCCState{schema_version:string;state_id:string;step:number;compute_root:HashHex;memory_root:HashHex;vector_clock:Record<string,number>;governance_weights:number[];failure_mode:number;audit_hash:HashHex;risk_vector:number[];lineage_root:HashHex;protected_root:HashHex}
export interface CanonicalEvent{schema_version:string;event_id:string;kind:string;producer:string;step:number;parent_hash:HashHex;payload_hash:HashHex;attributes:Record<string,string>}
export interface AuditEvent{schema_version:string;step_id:string;prev_audit_hash:HashHex;event_hash:HashHex;prev_state_hash:HashHex;next_state_body_hash:HashHex;checker_version:string;descriptor_hash:HashHex}
export interface POBundle{schema_version:string;checker_version:string;step_id:string;mode:StepMode;dom:boolean;inv:boolean;identity:boolean;governance:boolean;risk:boolean;audit:boolean;isolation:boolean;refinement:boolean;prev_state_hash:HashHex;next_state_hash:HashHex;event_hash:HashHex;audit_event_hash:HashHex;authorized_meta_path:boolean;recovery_path:boolean;witness_refs:Record<string,string>}
export interface ExecutionEnv{expected_po_schema:string;expected_state_schema:string;expected_event_schema:string;expected_audit_schema:string;checker_version:string;descriptor_hash:HashHex;numerical_mode:string;simplex_epsilon:number;risk_halt_threshold:number;max_governance_drift:number;max_risk_value:number;expected_build_id:string}
export interface Fixture{name:string;env:ExecutionEnv;prev:SCCState;event:CanonicalEvent;next:SCCState;audit_event:AuditEvent;po:POBundle;hashes:Record<string,string>;expected:{accepted:boolean;error:string|null}}
export const ZERO='00'.repeat(32); type Err='SchemaMismatch'|'VersionMismatch'|'MissingRequiredField'|'HashVerificationFailed'|'InvalidStepMode'|'ProtectedMutation'|'HaltViolation'|'GovernanceSimplexViolation'|'RiskThresholdBreach'|'AuditChainBroken'|'RefinementViolation'|'DomainViolation'|'LineageViolation';
class W{chunks:Buffer[]=[]; raw(b:Buffer|Uint8Array){this.chunks.push(Buffer.from(b))} bytes(){return Buffer.concat(this.chunks)} u8(x:number){const b=Buffer.alloc(1); b.writeUInt8(x); this.raw(b)} bool(x:boolean){if(typeof x!=='boolean')throw Error('bool'); this.u8(x?1:0)} u32(x:number){const b=Buffer.alloc(4); b.writeUInt32BE(x); this.raw(b)} u64(x:number){const b=Buffer.alloc(8); b.writeBigUInt64BE(BigInt(x)); this.raw(b)} str(s:string){const b=Buffer.from(s,'utf8'); this.u32(b.length); this.raw(b)} tag(s:string){this.str(s)} h(h:string){if(!/^[0-9a-fA-F]{64}$/.test(h))throw Error('hash'); this.raw(Buffer.from(h,'hex'))} f64(x:number){if(!Number.isFinite(x))throw Error('f64'); const b=Buffer.alloc(8); b.writeDoubleBE(Object.is(x,-0)?0:x); this.raw(b)} f64v(xs:number[]){this.u32(xs.length); for(const x of xs)this.f64(x)} smap(m:Record<string,string>){const ks=Object.keys(m??{}).sort(); this.u32(ks.length); for(const k of ks){this.str(k); this.str(String(m[k]))}} clock(m:Record<string,number>){const ks=Object.keys(m??{}).sort(); this.u32(ks.length); for(const k of ks){this.str(k); this.u64(m[k])}}}
export const sha256Hex=(b:Buffer|Uint8Array)=>createHash('sha256').update(b).digest('hex');
export function deriveRoot(label:string,...parts:string[]):HashHex{const w=new W(); w.tag('SCC-DERIVE-v1'); w.str(label); w.u32(parts.length); for(const p of parts){if(/^[0-9a-fA-F]{64}$/.test(p)){w.u8(1); w.h(p)}else{w.u8(0); w.str(p)}} return sha256Hex(w.bytes())}
export function stateBytes(s:SCCState,includeAudit=true){const w=new W(); w.tag('SCC-STATE-v1'); w.str(s.schema_version); w.str(s.state_id); w.u64(s.step); w.h(s.compute_root); w.h(s.memory_root); w.clock(s.vector_clock); w.f64v(s.governance_weights); w.u8(s.failure_mode); w.h(includeAudit?s.audit_hash:ZERO); w.f64v(s.risk_vector); w.h(s.lineage_root); w.h(s.protected_root); return w.bytes()} export const stateHash=(s:SCCState)=>sha256Hex(stateBytes(s,true)); export const stateBodyHash=(s:SCCState)=>sha256Hex(stateBytes(s,false));
export function eventBytes(e:CanonicalEvent){const w=new W(); w.tag('SCC-EVENT-v1'); w.str(e.schema_version); w.str(e.event_id); w.str(e.kind); w.str(e.producer); w.u64(e.step); w.h(e.parent_hash); w.h(e.payload_hash); w.smap(e.attributes??{}); return w.bytes()} export const eventHash=(e:CanonicalEvent)=>sha256Hex(eventBytes(e));
export function auditEventBytes(a:AuditEvent){const w=new W(); w.tag('SCC-AUDIT-EVENT-v1'); w.str(a.schema_version); w.str(a.step_id); w.h(a.prev_audit_hash); w.h(a.event_hash); w.h(a.prev_state_hash); w.h(a.next_state_body_hash); w.str(a.checker_version); w.h(a.descriptor_hash); return w.bytes()} export const auditEventHash=(a:AuditEvent)=>sha256Hex(auditEventBytes(a));
export function poBytes(po:POBundle){const w=new W(); w.tag('SCC-PO-BUNDLE-v1'); w.str(po.schema_version); w.str(po.checker_version); w.str(po.step_id); w.str(po.mode); for(const k of ['dom','inv','identity','governance','risk','audit','isolation','refinement'] as const)w.bool(po[k]); for(const k of ['prev_state_hash','next_state_hash','event_hash','audit_event_hash'] as const)w.h(po[k]); w.bool(po.authorized_meta_path); w.bool(po.recovery_path); w.smap(po.witness_refs??{}); return w.bytes()} export const poHash=(po:POBundle)=>sha256Hex(poBytes(po));
export const validSimplex=(w:number[],eps:number)=>Array.isArray(w)&&w.length>0&&w.every(Number.isFinite)&&w.every(x=>x>=-eps)&&Math.abs(w.reduce((a,b)=>a+b,0)-1)<=eps; export const l2Drift=(a:number[],b:number[])=>a.length===b.length?Math.sqrt(a.reduce((s,x,i)=>s+(x-b[i])**2,0)):Infinity;
export function projectToSimplex(input:number[]){if(input.some(x=>!Number.isFinite(x)))throw Error('nonfinite'); const d=input.length; if(!d)return []; const sorted=[...input].sort((a,b)=>b-a); let cssv=0,rho=0; for(let i=0;i<d;i++){cssv+=sorted[i]; const t=(cssv-1)/(i+1); if(i===d-1||t>=sorted[i+1]){rho=i;break}} const theta=(sorted.slice(0,rho+1).reduce((a,b)=>a+b,0)-1)/(rho+1); let out=input.map(x=>Math.max(0,x-theta)); const sum=out.reduce((a,b)=>a+b,0); return sum>1e-12?out.map(x=>x/sum):Array.from({length:d},()=>1/d)}
function expAudit(po:POBundle,prev:SCCState,next:SCCState,e:CanonicalEvent,env:ExecutionEnv):AuditEvent{const nb={...next,audit_hash:ZERO}; return {schema_version:env.expected_audit_schema,step_id:po.step_id,prev_audit_hash:prev.audit_hash,event_hash:eventHash(e),prev_state_hash:stateHash(prev),next_state_body_hash:stateBodyHash(nb),checker_version:po.checker_version,descriptor_hash:env.descriptor_hash}}
function aeEq(a:AuditEvent,b:AuditEvent){return a.schema_version===b.schema_version&&a.step_id===b.step_id&&a.prev_audit_hash===b.prev_audit_hash&&a.event_hash===b.event_hash&&a.prev_state_hash===b.prev_state_hash&&a.next_state_body_hash===b.next_state_body_hash&&a.checker_version===b.checker_version&&a.descriptor_hash===b.descriptor_hash}
function auditOk(po:POBundle,prev:SCCState,next:SCCState,e:CanonicalEvent,ae:AuditEvent,env:ExecutionEnv){const ex=expAudit(po,prev,next,e,env); const h=auditEventHash(ae); return aeEq(ae,ex)&&po.audit_event_hash===h&&next.audit_hash===h}
function norm(s:SCCState){return {compute_root:s.compute_root,memory_root:s.memory_root,vector_clock:{...s.vector_clock},governance_weights:[...s.governance_weights],failure_mode:s.failure_mode,risk_vector:[...s.risk_vector],protected_root:s.protected_root}}
function vecEq(a:number[],b:number[],eps:number){return a.length===b.length&&a.every((x,i)=>Math.abs(x-b[i])<=eps)} function clockEq(a:Record<string,number>,b:Record<string,number>){const ak=Object.keys(a).sort(),bk=Object.keys(b).sort(); return ak.length===bk.length&&ak.every((k,i)=>k===bk[i]&&a[k]===b[k])}
function normEq(a:any,b:any,eps:number){return a.compute_root===b.compute_root&&a.memory_root===b.memory_root&&clockEq(a.vector_clock,b.vector_clock)&&vecEq(a.governance_weights,b.governance_weights,eps)&&a.failure_mode===b.failure_mode&&vecEq(a.risk_vector,b.risk_vector,eps)&&a.protected_root===b.protected_root}
function expectedNorm(prev:SCCState,e:CanonicalEvent,env:ExecutionEnv){const n=norm(prev); n.compute_root=deriveRoot('compute',prev.compute_root,e.payload_hash); n.vector_clock[e.producer]=(n.vector_clock[e.producer]??0)+1; if(e.kind==='risk_signal'&&n.risk_vector.length)n.risk_vector[0]=Math.min(env.max_risk_value,n.risk_vector[0]+0.1); if(n.risk_vector.reduce((a,b)=>a+b,0)>=env.risk_halt_threshold)n.failure_mode=3; return n}
function classify(prev:SCCState,next:SCCState,e:CanonicalEvent,env:ExecutionEnv):StepMode|null{const p=norm(prev),n=norm(next),ex=expectedNorm(prev,e,env); if(normEq(n,ex,env.simplex_epsilon))return 'Exact'; if(normEq(n,p,env.simplex_epsilon))return 'Stutter'; const stable=n.compute_root===ex.compute_root&&n.memory_root===ex.memory_root&&clockEq(n.vector_clock,ex.vector_clock)&&vecEq(n.governance_weights,ex.governance_weights,env.simplex_epsilon)&&n.protected_root===ex.protected_root; if(stable&&n.risk_vector.reduce((a,b)=>a+b,0)<=ex.risk_vector.reduce((a,b)=>a+b,0)+env.simplex_epsilon&&n.failure_mode>=ex.failure_mode)return 'SafeRefined'; return null}
const req=['dom','inv','identity','governance','risk','audit','isolation','refinement'] as const; const fail=(error:Err)=>({ok:false,error});
export function accepts(po:POBundle,prev:SCCState,next:SCCState,e:CanonicalEvent,ae:AuditEvent,env:ExecutionEnv):{ok:boolean,error:Err|null}{try{if(po.schema_version!==env.expected_po_schema||e.schema_version!==env.expected_event_schema||ae.schema_version!==env.expected_audit_schema)return fail('SchemaMismatch'); if(po.checker_version!==env.checker_version)return fail('VersionMismatch'); if(!['Exact','Stutter','SafeRefined'].includes(po.mode))return fail('InvalidStepMode'); if(!req.every(k=>po[k]===true))return fail('MissingRequiredField'); if(po.prev_state_hash!==stateHash(prev)||po.next_state_hash!==stateHash(next)||po.event_hash!==eventHash(e))return fail('HashVerificationFailed'); const domain=(s:SCCState)=>s.schema_version===env.expected_state_schema&&Number.isInteger(s.failure_mode)&&s.failure_mode>=0&&s.failure_mode<=3&&validSimplex(s.governance_weights,env.simplex_epsilon)&&s.risk_vector.length>0&&s.risk_vector.every(x=>Number.isFinite(x)&&x>=0&&x<=env.max_risk_value); if(!domain(prev)||!domain(next))return fail('DomainViolation'); if(!po.authorized_meta_path&&prev.protected_root!==next.protected_root)return fail('ProtectedMutation'); if((prev.failure_mode===3&&!po.recovery_path&&next.failure_mode!==3)||(!po.recovery_path&&next.failure_mode<prev.failure_mode))return fail('HaltViolation'); if(!validSimplex(next.governance_weights,env.simplex_epsilon)||l2Drift(prev.governance_weights,next.governance_weights)>env.max_governance_drift+env.simplex_epsilon)return fail('GovernanceSimplexViolation'); if(next.risk_vector.reduce((a,b)=>a+b,0)>=env.risk_halt_threshold&&next.failure_mode!==3)return fail('RiskThresholdBreach'); if(next.lineage_root!==deriveRoot('lineage',prev.lineage_root,eventHash(e)))return fail('LineageViolation'); if(!auditOk(po,prev,next,e,ae,env))return fail('AuditChainBroken'); if(classify(prev,next,e,env)!==po.mode)return fail('RefinementViolation'); return {ok:true,error:null}}catch{return fail('HashVerificationFailed')}}
export function replay(steps:{po:POBundle;prev:SCCState;next:SCCState;event:CanonicalEvent;audit_event:AuditEvent}[],env:ExecutionEnv){if(!steps.length)throw Error('empty'); let cur=steps[0].prev; for(const s of steps){if(JSON.stringify(s.prev)!==JSON.stringify(cur))throw Error('discontinuity'); const r=accepts(s.po,s.prev,s.next,s.event,s.audit_event,env); if(!r.ok)throw Error(String(r.error)); cur=s.next} return cur}
